micronaut:
  application:
    name: foosbot
  server:
    port: -1

datasources:
  default:
    url: jdbc:sqlite:${FOOSBOT_DB_PATH:./foosbot.db}
    driver-class-name: org.sqlite.JDBC
    maximum-pool-size: 1

slack:
  bot-token: ${SLACK_BOT_TOKEN}
  app-token: ${SLACK_APP_TOKEN}
  signing-secret: ${SLACK_SIGNING_SECRET}
